liTest run started
leTest scala.scalanative.junit.ExceptionEverywhere failed: java.lang.AssertionError: before class, took <TIME>
e2scala.scalanative.junit.ExceptionEverywhere
leTest scala.scalanative.junit.ExceptionEverywhere failed: java.lang.AssertionError: after class, took <TIME>
liTest run finished: 2 failed, 0 ignored, 0 total, <TIME>
d
